<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Satish-ka-MacBook-Air.local" failures="2" tests="3" name="Submit Order Test" time="14.802" errors="0" timestamp="2024-12-03T18:19:35 IST">
  <testcase classname="framework.SubmitOrder" name="submitOrder" time="4.595">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at framework.SubmitOrder.submitOrder(SubmitOrder.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- submitOrder -->
  <testcase classname="framework.SubmitOrder" name="submitOrder" time="4.816">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at framework.SubmitOrder.submitOrder(SubmitOrder.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- submitOrder -->
  <testcase classname="framework.SubmitOrder" name="orderHistoryTest" time="0.001">
    <skipped/>
  </testcase> <!-- orderHistoryTest -->
</testsuite> <!-- Submit Order Test -->
